// <auto-generated />
namespace BSG.Seyhoon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initailcommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initailcommit));
        
        string IMigrationMetadata.Id
        {
            get { return "202202021158021_initail-commit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
