namespace BSG.Seyhoon.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class initailcommit : DbMigration
    {
        public override void Up()
        {
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.YearMonthDays", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.YearMonthDays", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.SqlCommands", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.SqlCommands", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.GSMModems", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.GSMModems", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.EvaluationParams", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.EvaluationParams", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.CalendarMonths", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.CalendarMonths", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.WorkshiftDetails", "WorkshiftId", "dbo.Workshifts");
            DropForeignKey("dbo.Workshifts", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Workshifts", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.WorkshiftDetails", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.WorkshiftDetails", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Countries", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Countries", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.RoleUsers", "User_Id", "dbo.Users");
            DropForeignKey("dbo.RoleUsers", "Role_Id", "dbo.Roles");
            DropForeignKey("dbo.RolesInPermissions", "RoleId", "dbo.Roles");
            DropForeignKey("dbo.MenusInRoles", "RoleId", "dbo.Roles");
            DropForeignKey("dbo.MenusInRoles", "MenuId", "dbo.Menus");
            DropForeignKey("dbo.UserMenus", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserMenus", "MenuId", "dbo.Menus");
            DropForeignKey("dbo.UserMenus", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.UserMenus", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.RoleMenus", "RoleId", "dbo.Roles");
            DropForeignKey("dbo.RoleMenus", "MenuId", "dbo.Menus");
            DropForeignKey("dbo.RoleMenus", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.RoleMenus", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PermissionsInMenus", "MenuId", "dbo.Menus");
            DropForeignKey("dbo.Menus", "ParentMenuId", "dbo.Menus");
            DropForeignKey("dbo.Menus", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Menus", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.MenusInRoles", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Users", "PeopleId", "dbo.People");
            DropForeignKey("dbo.Incidents", "VisitUserId", "dbo.Users");
            DropForeignKey("dbo.Incidents", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Incidents", "IncidentTypeId", "dbo.IncidentTypes");
            DropForeignKey("dbo.IncidentTypes", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.IncidentTypes", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.IncidentTypes", "ParentIncidentTypeId", "dbo.IncidentTypes");
            DropForeignKey("dbo.Incidents", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Incidents", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.EMDetails", "User_Id", "dbo.Users");
            DropForeignKey("dbo.AttendanceRequests", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleWorkshifts", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleWorkshifts", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleWorkshifts", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleTimesheets", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleTimesheets", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleTimesheets", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleTimesheetMonths", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleTimesheetMonths", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleTimesheetMonths", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleDocs", "PeopleDocTypeId", "dbo.PeopleDocTypes");
            DropForeignKey("dbo.PeopleDocTypes", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleDocTypes", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleDocs", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleDocs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleDocs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleAttendances", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleAttendances", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleAttendances", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleAssessments", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleAssessments", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleAssessments", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleAssessments", "AssessmentParameterId", "dbo.AssessmentParameters");
            DropForeignKey("dbo.AssessmentParameters", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.AssessmentParameters", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.People", "ParentPeopleId", "dbo.People");
            DropForeignKey("dbo.People", "OrgLevelId", "dbo.OrgLevels");
            DropForeignKey("dbo.OrgLevels", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.OrgLevels", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.People", "OrgChartId", "dbo.OrgCharts");
            DropForeignKey("dbo.OrgCharts", "ParentOrgChartId", "dbo.OrgCharts");
            DropForeignKey("dbo.OrgCharts", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.OrgCharts", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.People", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.People", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.People", "CountryId", "dbo.Countries");
            DropForeignKey("dbo.People", "ContractorId", "dbo.Contractors");
            DropForeignKey("dbo.People", "BranchDepartmentId", "dbo.BranchDepartments");
            DropForeignKey("dbo.People", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.GuardBoards", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardBoards", "GuardOfficer3Id", "dbo.People");
            DropForeignKey("dbo.GuardBoards", "GuardOfficer2Id", "dbo.People");
            DropForeignKey("dbo.GuardBoards", "GuardOfficer1Id", "dbo.People");
            DropForeignKey("dbo.GuardBoards", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardBoards", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.Branches", "TownshipId", "dbo.Townships");
            DropForeignKey("dbo.Branches", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardPlaces", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardBoardPlaces", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardBoardPlaces", "GuardPlaceId", "dbo.GuardPlaces");
            DropForeignKey("dbo.GuardBoardPlacePasses", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardBoardPlacePassDetails", "GuardId", "dbo.People");
            DropForeignKey("dbo.GuardBoardPlacePassDetails", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardBoardPlacePassDetails", "GuardBoardPlacePassId", "dbo.GuardBoardPlacePasses");
            DropForeignKey("dbo.GuardBoardPlacePassDetails", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardBoardPlacePasses", "GuardBoardPlaceId", "dbo.GuardBoardPlaces");
            DropForeignKey("dbo.GuardBoardPlacePasses", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardBoardPlaces", "GuardBoardId", "dbo.GuardBoards");
            DropForeignKey("dbo.GuardBoardPlaces", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardPlaces", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.GuardPlaces", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.Events", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Events", "FirstReadUserId", "dbo.Users");
            DropForeignKey("dbo.Events", "EventTypeId", "dbo.EventTypes");
            DropForeignKey("dbo.EventTypes", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.EventTypes", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Events", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Events", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.StockDocDetails", "StockDocId", "dbo.StockDocs");
            DropForeignKey("dbo.StockDocDetails", "ReturnConfirmUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocDetails", "ProductId", "dbo.Products");
            DropForeignKey("dbo.StockDocDetails", "MatId", "dbo.Mats");
            DropForeignKey("dbo.StockDocDetails", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocDetails", "DeviceId", "dbo.Devices");
            DropForeignKey("dbo.PlannedPMs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.DonePMs", "PlannedPMId", "dbo.PlannedPMs");
            DropForeignKey("dbo.DonePMs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.DonePMJobs", "PMStaticJobId", "dbo.PMStaticJobs");
            DropForeignKey("dbo.PlannedPMDetails", "PMStaticJobId", "dbo.PMStaticJobs");
            DropForeignKey("dbo.PlannedPMDetails", "PlannedPMId", "dbo.PlannedPMs");
            DropForeignKey("dbo.PlannedPMDetails", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PlannedPMDetails", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PMStaticJobs", "MatGroupId", "dbo.MatGroups");
            DropForeignKey("dbo.PMStaticJobs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PMStaticJobs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.DonePMJobs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.DonePMJobs", "DonePMId", "dbo.DonePMs");
            DropForeignKey("dbo.DonePMJobs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.DonePMs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PlannedPMs", "DeviceId", "dbo.Devices");
            DropForeignKey("dbo.PlannedPMs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Devices", "MatGroupId", "dbo.MatGroups");
            DropForeignKey("dbo.Devices", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.EMs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.EMs", "EMStaticJobId", "dbo.EMStaticJobs");
            DropForeignKey("dbo.TaskOrderReferences", "TaskOrderId", "dbo.TaskOrders");
            DropForeignKey("dbo.TaskOrderReferences", "ReciverUserId", "dbo.Users");
            DropForeignKey("dbo.TaskOrderReferences", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.TaskOrderReferences", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.TaskOrderDetails", "TaskOrderId", "dbo.TaskOrders");
            DropForeignKey("dbo.TaskOrderDetails", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.TaskOrderDetails", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.TaskOrders", "ReciverUserId", "dbo.Users");
            DropForeignKey("dbo.TaskOrders", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.TaskOrders", "EMStaticJobId", "dbo.EMStaticJobs");
            DropForeignKey("dbo.TaskOrders", "DoneUserId", "dbo.Users");
            DropForeignKey("dbo.TaskOrders", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.EMStaticJobs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.EMStaticJobs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.EMStaticJobs", "ParentEMStaticJobId", "dbo.EMStaticJobs");
            DropForeignKey("dbo.EMDetails", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.EMDetails", "EMId", "dbo.EMs");
            DropForeignKey("dbo.EMDetails", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.EMs", "DoneUserId", "dbo.Users");
            DropForeignKey("dbo.EMs", "DeviceId", "dbo.Devices");
            DropForeignKey("dbo.EMs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.EMs", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.DeviceTechSpecs", "MatGroupTechSpecId", "dbo.MatGroupTechSpecs");
            DropForeignKey("dbo.MatGroups", "ParentMatGroupId", "dbo.MatGroups");
            DropForeignKey("dbo.Mats", "MatUnitId", "dbo.MatUnits");
            DropForeignKey("dbo.Products", "MatUnitId", "dbo.MatUnits");
            DropForeignKey("dbo.Products", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Products", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.MatUnits", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.MatUnits", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.MatInvs", "MatId", "dbo.Mats");
            DropForeignKey("dbo.MatInvs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.MatInvs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.MatInvs", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.Mats", "MatGroupId", "dbo.MatGroups");
            DropForeignKey("dbo.Mats", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Mats", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.MatGroupTechSpecs", "MatGroupId", "dbo.MatGroups");
            DropForeignKey("dbo.MatGroups", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.MatGroups", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.MatGroupTechSpecs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.MatGroupTechSpecs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.DeviceTechSpecs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.DeviceTechSpecs", "DeviceId", "dbo.Devices");
            DropForeignKey("dbo.DeviceTechSpecs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Devices", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Devices", "BrandId", "dbo.Brands");
            DropForeignKey("dbo.Brands", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Brands", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Devices", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.StockDocDetails", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocs", "SourceConfirmUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocs", "SourceBranchId", "dbo.Branches");
            DropForeignKey("dbo.StockDocs", "PlateCharacterId", "dbo.PlateCharacters");
            DropForeignKey("dbo.StockDocs", "OrgCarId", "dbo.OrgCars");
            DropForeignKey("dbo.StockDocs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocs", "ExitConfirmUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocs", "EntranceConfirmUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocs", "DriverId", "dbo.People");
            DropForeignKey("dbo.StockDocs", "DestConfirmUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocs", "DestBranchId", "dbo.Branches");
            DropForeignKey("dbo.StockDocs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocs", "CarTypeId", "dbo.CarTypes");
            DropForeignKey("dbo.OrgCars", "PlateCharacterId", "dbo.PlateCharacters");
            DropForeignKey("dbo.OrgCars", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.OrgCars", "DriverId", "dbo.People");
            DropForeignKey("dbo.OrgCars", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.OrgCars", "ColoringId", "dbo.Colorings");
            DropForeignKey("dbo.OrgCars", "CarTypeId", "dbo.CarTypes");
            DropForeignKey("dbo.OrgCars", "CarBrandId", "dbo.CarBrands");
            DropForeignKey("dbo.PeopleCars", "PlateCharacterId", "dbo.PlateCharacters");
            DropForeignKey("dbo.PlateCharacters", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PlateCharacters", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleCars", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleCars", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleCars", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleCars", "ColoringId", "dbo.Colorings");
            DropForeignKey("dbo.Colorings", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Colorings", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleCars", "CarTypeId", "dbo.CarTypes");
            DropForeignKey("dbo.PeopleCars", "CarBrandId", "dbo.CarBrands");
            DropForeignKey("dbo.CarBrands", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.CarBrands", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.OrgCars", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.CarTypes", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.CarTypes", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.StockDocs", "CarrierPeopleId", "dbo.People");
            DropForeignKey("dbo.Branches", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Branches", "ContractorId", "dbo.Contractors");
            DropForeignKey("dbo.Contractors", "TownshipId", "dbo.Townships");
            DropForeignKey("dbo.Townships", "ProvinceId", "dbo.Provinces");
            DropForeignKey("dbo.Provinces", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Provinces", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Provinces", "CountryId", "dbo.Countries");
            DropForeignKey("dbo.Townships", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Townships", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Contractors", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Contractors", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.ContractorContacts", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.ContractorContacts", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.ContractorContacts", "ContractorId", "dbo.Contractors");
            DropForeignKey("dbo.CheckLists", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.CheckLists", "DailyCheckListId", "dbo.DailyCheckLists");
            DropForeignKey("dbo.CheckLists", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.CheckListDets", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.CheckListDets", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.CheckListDets", "CheckListTypeItemId", "dbo.CheckListTypeItems");
            DropForeignKey("dbo.CheckListTypeItems", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.CheckListTypeItems", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.CheckListTypeItems", "CheckListTypeId", "dbo.CheckListTypes");
            DropForeignKey("dbo.PlannedCheckLists", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.DailyCheckLists", "PlannedCheckListId", "dbo.PlannedCheckLists");
            DropForeignKey("dbo.DailyCheckLists", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.DailyCheckLists", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PlannedCheckLists", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PlannedCheckLists", "CheckListTypeId", "dbo.CheckListTypes");
            DropForeignKey("dbo.CheckListTypes", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.CheckListTypes", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.CheckListDets", "CheckListId", "dbo.CheckLists");
            DropForeignKey("dbo.CheckLists", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.BranchIPs", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.BranchIPs", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.BranchIPs", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.PeopleTrafficLicenseWeekDays", "TimesheetWeekDayId", "dbo.TimesheetWeekDays");
            DropForeignKey("dbo.TimesheetCalendars", "TimesheetWeekDayId", "dbo.TimesheetWeekDays");
            DropForeignKey("dbo.TimesheetCalendars", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.TimesheetCalendars", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.TimesheetWeekDays", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.TimesheetWeekDays", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleTrafficLicenseWeekDays", "PeopleTrafficLicenseId", "dbo.PeopleTrafficLicenses");
            DropForeignKey("dbo.PeopleTrafficLicenses", "PeopleId", "dbo.People");
            DropForeignKey("dbo.PeopleTrafficLicenses", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleTrafficLicenses", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.PeopleTrafficLicenses", "BranchDepartmentId", "dbo.BranchDepartments");
            DropForeignKey("dbo.PeopleTrafficLicenses", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.BranchDepartments", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.BranchDepartments", "BranchDepartment_Id", "dbo.BranchDepartments");
            DropForeignKey("dbo.InvitationDepartments", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.InvitationDepartments", "InvitationId", "dbo.Invitations");
            DropForeignKey("dbo.Invitations", "ManagerConfirmUserId", "dbo.Users");
            DropForeignKey("dbo.Invitations", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.Invitations", "InvitationTypeId", "dbo.InvitationTypes");
            DropForeignKey("dbo.InvitationTypes", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.InvitationTypes", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Invitations", "HostPeopleId", "dbo.People");
            DropForeignKey("dbo.Invitations", "GuestPeopleId", "dbo.People");
            DropForeignKey("dbo.Invitations", "GateExitUserId", "dbo.Users");
            DropForeignKey("dbo.Invitations", "GateEntranceUserId", "dbo.Users");
            DropForeignKey("dbo.Invitations", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.Invitations", "BranchDepartmentId", "dbo.BranchDepartments");
            DropForeignKey("dbo.InvitationDepartments", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.InvitationDepartments", "BranchDepartmentId", "dbo.BranchDepartments");
            DropForeignKey("dbo.BranchDepartments", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.BranchDepartments", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.BranchContacts", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.BranchContacts", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.BranchContacts", "BranchId", "dbo.Branches");
            DropForeignKey("dbo.GuardBoards", "AuxiliaryGuardOfficerId", "dbo.People");
            DropForeignKey("dbo.AttendanceRequests", "LastUpdateUserId", "dbo.Users");
            DropForeignKey("dbo.AttendanceRequests", "CreateUserId", "dbo.Users");
            DropForeignKey("dbo.AttendanceRequests", "ConfirmUserId", "dbo.Users");
            DropIndex("dbo.RoleUsers", new[] { "User_Id" });
            DropIndex("dbo.RoleUsers", new[] { "Role_Id" });
            DropIndex("dbo.YearMonthDays", new[] { "LastUpdateUserId" });
            DropIndex("dbo.YearMonthDays", new[] { "CreateUserId" });
            DropIndex("dbo.SqlCommands", new[] { "LastUpdateUserId" });
            DropIndex("dbo.SqlCommands", new[] { "CreateUserId" });
            DropIndex("dbo.GSMModems", new[] { "LastUpdateUserId" });
            DropIndex("dbo.GSMModems", new[] { "CreateUserId" });
            DropIndex("dbo.EvaluationParams", new[] { "LastUpdateUserId" });
            DropIndex("dbo.EvaluationParams", new[] { "CreateUserId" });
            DropIndex("dbo.CalendarMonths", new[] { "LastUpdateUserId" });
            DropIndex("dbo.CalendarMonths", new[] { "CreateUserId" });
            DropIndex("dbo.Workshifts", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Workshifts", new[] { "CreateUserId" });
            DropIndex("dbo.WorkshiftDetails", new[] { "LastUpdateUserId" });
            DropIndex("dbo.WorkshiftDetails", new[] { "CreateUserId" });
            DropIndex("dbo.WorkshiftDetails", new[] { "WorkshiftId" });
            DropIndex("dbo.RolesInPermissions", new[] { "RoleId" });
            DropIndex("dbo.UserMenus", new[] { "LastUpdateUserId" });
            DropIndex("dbo.UserMenus", new[] { "CreateUserId" });
            DropIndex("dbo.UserMenus", new[] { "UserId" });
            DropIndex("dbo.UserMenus", new[] { "MenuId" });
            DropIndex("dbo.RoleMenus", new[] { "LastUpdateUserId" });
            DropIndex("dbo.RoleMenus", new[] { "CreateUserId" });
            DropIndex("dbo.RoleMenus", new[] { "MenuId" });
            DropIndex("dbo.RoleMenus", new[] { "RoleId" });
            DropIndex("dbo.PermissionsInMenus", new[] { "MenuId" });
            DropIndex("dbo.Menus", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Menus", new[] { "CreateUserId" });
            DropIndex("dbo.Menus", new[] { "ParentMenuId" });
            DropIndex("dbo.MenusInRoles", new[] { "CreateUserId" });
            DropIndex("dbo.MenusInRoles", new[] { "RoleId" });
            DropIndex("dbo.MenusInRoles", new[] { "MenuId" });
            DropIndex("dbo.IncidentTypes", new[] { "LastUpdateUserId" });
            DropIndex("dbo.IncidentTypes", new[] { "CreateUserId" });
            DropIndex("dbo.IncidentTypes", new[] { "ParentIncidentTypeId" });
            DropIndex("dbo.Incidents", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Incidents", new[] { "CreateUserId" });
            DropIndex("dbo.Incidents", new[] { "VisitUserId" });
            DropIndex("dbo.Incidents", new[] { "BranchId" });
            DropIndex("dbo.Incidents", new[] { "IncidentTypeId" });
            DropIndex("dbo.PeopleWorkshifts", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleWorkshifts", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleWorkshifts", new[] { "PeopleId" });
            DropIndex("dbo.PeopleTimesheets", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleTimesheets", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleTimesheets", new[] { "PeopleId" });
            DropIndex("dbo.PeopleTimesheetMonths", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleTimesheetMonths", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleTimesheetMonths", new[] { "PeopleId" });
            DropIndex("dbo.PeopleDocTypes", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleDocTypes", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleDocs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleDocs", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleDocs", new[] { "PeopleDocTypeId" });
            DropIndex("dbo.PeopleDocs", new[] { "PeopleId" });
            DropIndex("dbo.PeopleAttendances", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleAttendances", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleAttendances", new[] { "PeopleId" });
            DropIndex("dbo.AssessmentParameters", new[] { "LastUpdateUserId" });
            DropIndex("dbo.AssessmentParameters", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleAssessments", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleAssessments", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleAssessments", new[] { "AssessmentParameterId" });
            DropIndex("dbo.PeopleAssessments", new[] { "PeopleId" });
            DropIndex("dbo.OrgLevels", new[] { "LastUpdateUserId" });
            DropIndex("dbo.OrgLevels", new[] { "CreateUserId" });
            DropIndex("dbo.OrgCharts", new[] { "LastUpdateUserId" });
            DropIndex("dbo.OrgCharts", new[] { "CreateUserId" });
            DropIndex("dbo.OrgCharts", new[] { "ParentOrgChartId" });
            DropIndex("dbo.GuardBoardPlacePassDetails", new[] { "LastUpdateUserId" });
            DropIndex("dbo.GuardBoardPlacePassDetails", new[] { "CreateUserId" });
            DropIndex("dbo.GuardBoardPlacePassDetails", new[] { "GuardId" });
            DropIndex("dbo.GuardBoardPlacePassDetails", new[] { "GuardBoardPlacePassId" });
            DropIndex("dbo.GuardBoardPlacePasses", new[] { "LastUpdateUserId" });
            DropIndex("dbo.GuardBoardPlacePasses", new[] { "CreateUserId" });
            DropIndex("dbo.GuardBoardPlacePasses", new[] { "GuardBoardPlaceId" });
            DropIndex("dbo.GuardBoardPlaces", new[] { "LastUpdateUserId" });
            DropIndex("dbo.GuardBoardPlaces", new[] { "CreateUserId" });
            DropIndex("dbo.GuardBoardPlaces", new[] { "GuardPlaceId" });
            DropIndex("dbo.GuardBoardPlaces", new[] { "GuardBoardId" });
            DropIndex("dbo.GuardPlaces", new[] { "LastUpdateUserId" });
            DropIndex("dbo.GuardPlaces", new[] { "CreateUserId" });
            DropIndex("dbo.GuardPlaces", new[] { "BranchId" });
            DropIndex("dbo.EventTypes", new[] { "LastUpdateUserId" });
            DropIndex("dbo.EventTypes", new[] { "CreateUserId" });
            DropIndex("dbo.Events", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Events", new[] { "CreateUserId" });
            DropIndex("dbo.Events", new[] { "FirstReadUserId" });
            DropIndex("dbo.Events", new[] { "BranchId" });
            DropIndex("dbo.Events", new[] { "EventTypeId" });
            DropIndex("dbo.PlannedPMDetails", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PlannedPMDetails", new[] { "CreateUserId" });
            DropIndex("dbo.PlannedPMDetails", new[] { "PMStaticJobId" });
            DropIndex("dbo.PlannedPMDetails", new[] { "PlannedPMId" });
            DropIndex("dbo.PMStaticJobs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PMStaticJobs", new[] { "CreateUserId" });
            DropIndex("dbo.PMStaticJobs", new[] { "MatGroupId" });
            DropIndex("dbo.DonePMJobs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.DonePMJobs", new[] { "CreateUserId" });
            DropIndex("dbo.DonePMJobs", new[] { "PMStaticJobId" });
            DropIndex("dbo.DonePMJobs", new[] { "DonePMId" });
            DropIndex("dbo.DonePMs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.DonePMs", new[] { "CreateUserId" });
            DropIndex("dbo.DonePMs", new[] { "PlannedPMId" });
            DropIndex("dbo.PlannedPMs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PlannedPMs", new[] { "CreateUserId" });
            DropIndex("dbo.PlannedPMs", new[] { "DeviceId" });
            DropIndex("dbo.TaskOrderReferences", new[] { "LastUpdateUserId" });
            DropIndex("dbo.TaskOrderReferences", new[] { "CreateUserId" });
            DropIndex("dbo.TaskOrderReferences", new[] { "ReciverUserId" });
            DropIndex("dbo.TaskOrderReferences", new[] { "TaskOrderId" });
            DropIndex("dbo.TaskOrderDetails", new[] { "LastUpdateUserId" });
            DropIndex("dbo.TaskOrderDetails", new[] { "CreateUserId" });
            DropIndex("dbo.TaskOrderDetails", new[] { "TaskOrderId" });
            DropIndex("dbo.TaskOrders", new[] { "LastUpdateUserId" });
            DropIndex("dbo.TaskOrders", new[] { "CreateUserId" });
            DropIndex("dbo.TaskOrders", new[] { "DoneUserId" });
            DropIndex("dbo.TaskOrders", new[] { "ReciverUserId" });
            DropIndex("dbo.TaskOrders", new[] { "EMStaticJobId" });
            DropIndex("dbo.EMStaticJobs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.EMStaticJobs", new[] { "CreateUserId" });
            DropIndex("dbo.EMStaticJobs", new[] { "ParentEMStaticJobId" });
            DropIndex("dbo.EMDetails", new[] { "User_Id" });
            DropIndex("dbo.EMDetails", new[] { "LastUpdateUserId" });
            DropIndex("dbo.EMDetails", new[] { "CreateUserId" });
            DropIndex("dbo.EMDetails", new[] { "EMId" });
            DropIndex("dbo.EMs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.EMs", new[] { "CreateUserId" });
            DropIndex("dbo.EMs", new[] { "DoneUserId" });
            DropIndex("dbo.EMs", new[] { "EMStaticJobId" });
            DropIndex("dbo.EMs", new[] { "DeviceId" });
            DropIndex("dbo.EMs", new[] { "BranchId" });
            DropIndex("dbo.Products", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Products", new[] { "CreateUserId" });
            DropIndex("dbo.Products", new[] { "MatUnitId" });
            DropIndex("dbo.MatUnits", new[] { "LastUpdateUserId" });
            DropIndex("dbo.MatUnits", new[] { "CreateUserId" });
            DropIndex("dbo.MatInvs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.MatInvs", new[] { "CreateUserId" });
            DropIndex("dbo.MatInvs", new[] { "BranchId" });
            DropIndex("dbo.MatInvs", new[] { "MatId" });
            DropIndex("dbo.Mats", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Mats", new[] { "CreateUserId" });
            DropIndex("dbo.Mats", new[] { "MatUnitId" });
            DropIndex("dbo.Mats", new[] { "MatGroupId" });
            DropIndex("dbo.MatGroups", new[] { "LastUpdateUserId" });
            DropIndex("dbo.MatGroups", new[] { "CreateUserId" });
            DropIndex("dbo.MatGroups", new[] { "ParentMatGroupId" });
            DropIndex("dbo.MatGroupTechSpecs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.MatGroupTechSpecs", new[] { "CreateUserId" });
            DropIndex("dbo.MatGroupTechSpecs", new[] { "MatGroupId" });
            DropIndex("dbo.DeviceTechSpecs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.DeviceTechSpecs", new[] { "CreateUserId" });
            DropIndex("dbo.DeviceTechSpecs", new[] { "MatGroupTechSpecId" });
            DropIndex("dbo.DeviceTechSpecs", new[] { "DeviceId" });
            DropIndex("dbo.Brands", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Brands", new[] { "CreateUserId" });
            DropIndex("dbo.Devices", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Devices", new[] { "CreateUserId" });
            DropIndex("dbo.Devices", new[] { "BrandId" });
            DropIndex("dbo.Devices", new[] { "BranchId" });
            DropIndex("dbo.Devices", new[] { "MatGroupId" });
            DropIndex("dbo.StockDocDetails", new[] { "LastUpdateUserId" });
            DropIndex("dbo.StockDocDetails", new[] { "CreateUserId" });
            DropIndex("dbo.StockDocDetails", new[] { "ReturnConfirmUserId" });
            DropIndex("dbo.StockDocDetails", new[] { "DeviceId" });
            DropIndex("dbo.StockDocDetails", new[] { "ProductId" });
            DropIndex("dbo.StockDocDetails", new[] { "MatId" });
            DropIndex("dbo.StockDocDetails", new[] { "StockDocId" });
            DropIndex("dbo.PlateCharacters", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PlateCharacters", new[] { "CreateUserId" });
            DropIndex("dbo.Colorings", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Colorings", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleCars", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleCars", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleCars", new[] { "PlateCharacterId" });
            DropIndex("dbo.PeopleCars", new[] { "ColoringId" });
            DropIndex("dbo.PeopleCars", new[] { "CarBrandId" });
            DropIndex("dbo.PeopleCars", new[] { "CarTypeId" });
            DropIndex("dbo.PeopleCars", new[] { "PeopleId" });
            DropIndex("dbo.CarBrands", new[] { "LastUpdateUserId" });
            DropIndex("dbo.CarBrands", new[] { "CreateUserId" });
            DropIndex("dbo.OrgCars", new[] { "LastUpdateUserId" });
            DropIndex("dbo.OrgCars", new[] { "CreateUserId" });
            DropIndex("dbo.OrgCars", new[] { "PlateCharacterId" });
            DropIndex("dbo.OrgCars", new[] { "DriverId" });
            DropIndex("dbo.OrgCars", new[] { "ColoringId" });
            DropIndex("dbo.OrgCars", new[] { "CarBrandId" });
            DropIndex("dbo.OrgCars", new[] { "CarTypeId" });
            DropIndex("dbo.OrgCars", new[] { "BranchId" });
            DropIndex("dbo.CarTypes", new[] { "LastUpdateUserId" });
            DropIndex("dbo.CarTypes", new[] { "CreateUserId" });
            DropIndex("dbo.StockDocs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.StockDocs", new[] { "CreateUserId" });
            DropIndex("dbo.StockDocs", new[] { "DestConfirmUserId" });
            DropIndex("dbo.StockDocs", new[] { "SourceConfirmUserId" });
            DropIndex("dbo.StockDocs", new[] { "EntranceConfirmUserId" });
            DropIndex("dbo.StockDocs", new[] { "ExitConfirmUserId" });
            DropIndex("dbo.StockDocs", new[] { "CarTypeId" });
            DropIndex("dbo.StockDocs", new[] { "PlateCharacterId" });
            DropIndex("dbo.StockDocs", new[] { "DriverId" });
            DropIndex("dbo.StockDocs", new[] { "OrgCarId" });
            DropIndex("dbo.StockDocs", new[] { "CarrierPeopleId" });
            DropIndex("dbo.StockDocs", new[] { "DestBranchId" });
            DropIndex("dbo.StockDocs", new[] { "SourceBranchId" });
            DropIndex("dbo.Provinces", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Provinces", new[] { "CreateUserId" });
            DropIndex("dbo.Provinces", new[] { "CountryId" });
            DropIndex("dbo.Townships", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Townships", new[] { "CreateUserId" });
            DropIndex("dbo.Townships", new[] { "ProvinceId" });
            DropIndex("dbo.ContractorContacts", new[] { "LastUpdateUserId" });
            DropIndex("dbo.ContractorContacts", new[] { "CreateUserId" });
            DropIndex("dbo.ContractorContacts", new[] { "ContractorId" });
            DropIndex("dbo.Contractors", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Contractors", new[] { "CreateUserId" });
            DropIndex("dbo.Contractors", new[] { "TownshipId" });
            DropIndex("dbo.DailyCheckLists", new[] { "LastUpdateUserId" });
            DropIndex("dbo.DailyCheckLists", new[] { "CreateUserId" });
            DropIndex("dbo.DailyCheckLists", new[] { "PlannedCheckListId" });
            DropIndex("dbo.PlannedCheckLists", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PlannedCheckLists", new[] { "CreateUserId" });
            DropIndex("dbo.PlannedCheckLists", new[] { "CheckListTypeId" });
            DropIndex("dbo.CheckListTypes", new[] { "LastUpdateUserId" });
            DropIndex("dbo.CheckListTypes", new[] { "CreateUserId" });
            DropIndex("dbo.CheckListTypeItems", new[] { "LastUpdateUserId" });
            DropIndex("dbo.CheckListTypeItems", new[] { "CreateUserId" });
            DropIndex("dbo.CheckListTypeItems", new[] { "CheckListTypeId" });
            DropIndex("dbo.CheckListDets", new[] { "LastUpdateUserId" });
            DropIndex("dbo.CheckListDets", new[] { "CreateUserId" });
            DropIndex("dbo.CheckListDets", new[] { "CheckListTypeItemId" });
            DropIndex("dbo.CheckListDets", new[] { "CheckListId" });
            DropIndex("dbo.CheckLists", new[] { "LastUpdateUserId" });
            DropIndex("dbo.CheckLists", new[] { "CreateUserId" });
            DropIndex("dbo.CheckLists", new[] { "BranchId" });
            DropIndex("dbo.CheckLists", new[] { "DailyCheckListId" });
            DropIndex("dbo.BranchIPs", new[] { "LastUpdateUserId" });
            DropIndex("dbo.BranchIPs", new[] { "CreateUserId" });
            DropIndex("dbo.BranchIPs", new[] { "BranchId" });
            DropIndex("dbo.TimesheetCalendars", new[] { "LastUpdateUserId" });
            DropIndex("dbo.TimesheetCalendars", new[] { "CreateUserId" });
            DropIndex("dbo.TimesheetCalendars", new[] { "TimesheetWeekDayId" });
            DropIndex("dbo.TimesheetWeekDays", new[] { "LastUpdateUserId" });
            DropIndex("dbo.TimesheetWeekDays", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleTrafficLicenseWeekDays", new[] { "TimesheetWeekDayId" });
            DropIndex("dbo.PeopleTrafficLicenseWeekDays", new[] { "PeopleTrafficLicenseId" });
            DropIndex("dbo.PeopleTrafficLicenses", new[] { "LastUpdateUserId" });
            DropIndex("dbo.PeopleTrafficLicenses", new[] { "CreateUserId" });
            DropIndex("dbo.PeopleTrafficLicenses", new[] { "BranchDepartmentId" });
            DropIndex("dbo.PeopleTrafficLicenses", new[] { "BranchId" });
            DropIndex("dbo.PeopleTrafficLicenses", new[] { "PeopleId" });
            DropIndex("dbo.InvitationTypes", new[] { "LastUpdateUserId" });
            DropIndex("dbo.InvitationTypes", new[] { "CreateUserId" });
            DropIndex("dbo.Invitations", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Invitations", new[] { "CreateUserId" });
            DropIndex("dbo.Invitations", new[] { "GateExitUserId" });
            DropIndex("dbo.Invitations", new[] { "GateEntranceUserId" });
            DropIndex("dbo.Invitations", new[] { "ManagerConfirmUserId" });
            DropIndex("dbo.Invitations", new[] { "BranchDepartmentId" });
            DropIndex("dbo.Invitations", new[] { "GuestPeopleId" });
            DropIndex("dbo.Invitations", new[] { "HostPeopleId" });
            DropIndex("dbo.Invitations", new[] { "InvitationTypeId" });
            DropIndex("dbo.InvitationDepartments", new[] { "LastUpdateUserId" });
            DropIndex("dbo.InvitationDepartments", new[] { "CreateUserId" });
            DropIndex("dbo.InvitationDepartments", new[] { "BranchDepartmentId" });
            DropIndex("dbo.InvitationDepartments", new[] { "InvitationId" });
            DropIndex("dbo.BranchDepartments", new[] { "BranchDepartment_Id" });
            DropIndex("dbo.BranchDepartments", new[] { "LastUpdateUserId" });
            DropIndex("dbo.BranchDepartments", new[] { "CreateUserId" });
            DropIndex("dbo.BranchDepartments", new[] { "BranchId" });
            DropIndex("dbo.BranchContacts", new[] { "LastUpdateUserId" });
            DropIndex("dbo.BranchContacts", new[] { "CreateUserId" });
            DropIndex("dbo.BranchContacts", new[] { "BranchId" });
            DropIndex("dbo.Branches", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Branches", new[] { "CreateUserId" });
            DropIndex("dbo.Branches", new[] { "ContractorId" });
            DropIndex("dbo.Branches", new[] { "TownshipId" });
            DropIndex("dbo.GuardBoards", new[] { "LastUpdateUserId" });
            DropIndex("dbo.GuardBoards", new[] { "CreateUserId" });
            DropIndex("dbo.GuardBoards", new[] { "AuxiliaryGuardOfficerId" });
            DropIndex("dbo.GuardBoards", new[] { "GuardOfficer3Id" });
            DropIndex("dbo.GuardBoards", new[] { "GuardOfficer2Id" });
            DropIndex("dbo.GuardBoards", new[] { "GuardOfficer1Id" });
            DropIndex("dbo.GuardBoards", new[] { "BranchId" });
            DropIndex("dbo.People", new[] { "LastUpdateUserId" });
            DropIndex("dbo.People", new[] { "CreateUserId" });
            DropIndex("dbo.People", new[] { "CountryId" });
            DropIndex("dbo.People", new[] { "ParentPeopleId" });
            DropIndex("dbo.People", new[] { "ContractorId" });
            DropIndex("dbo.People", new[] { "OrgChartId" });
            DropIndex("dbo.People", new[] { "OrgLevelId" });
            DropIndex("dbo.People", new[] { "BranchDepartmentId" });
            DropIndex("dbo.People", new[] { "BranchId" });
            DropIndex("dbo.AttendanceRequests", new[] { "LastUpdateUserId" });
            DropIndex("dbo.AttendanceRequests", new[] { "CreateUserId" });
            DropIndex("dbo.AttendanceRequests", new[] { "ConfirmUserId" });
            DropIndex("dbo.AttendanceRequests", new[] { "PeopleId" });
            DropIndex("dbo.Users", new[] { "PeopleId" });
            DropIndex("dbo.Countries", new[] { "LastUpdateUserId" });
            DropIndex("dbo.Countries", new[] { "CreateUserId" });
            DropTable("dbo.RoleUsers");
            DropTable("dbo.YearMonthDays");
            DropTable("dbo.SqlCommands");
            DropTable("dbo.GSMModems");
            DropTable("dbo.EvaluationParams");
            DropTable("dbo.CalendarMonths");
            DropTable("dbo.Workshifts");
            DropTable("dbo.WorkshiftDetails");
            DropTable("dbo.RolesInPermissions");
            DropTable("dbo.UserMenus");
            DropTable("dbo.RoleMenus");
            DropTable("dbo.PermissionsInMenus");
            DropTable("dbo.Menus");
            DropTable("dbo.MenusInRoles");
            DropTable("dbo.Roles");
            DropTable("dbo.IncidentTypes");
            DropTable("dbo.Incidents");
            DropTable("dbo.PeopleWorkshifts");
            DropTable("dbo.PeopleTimesheets");
            DropTable("dbo.PeopleTimesheetMonths");
            DropTable("dbo.PeopleDocTypes");
            DropTable("dbo.PeopleDocs");
            DropTable("dbo.PeopleAttendances");
            DropTable("dbo.AssessmentParameters");
            DropTable("dbo.PeopleAssessments");
            DropTable("dbo.OrgLevels");
            DropTable("dbo.OrgCharts");
            DropTable("dbo.GuardBoardPlacePassDetails");
            DropTable("dbo.GuardBoardPlacePasses");
            DropTable("dbo.GuardBoardPlaces");
            DropTable("dbo.GuardPlaces");
            DropTable("dbo.EventTypes");
            DropTable("dbo.Events");
            DropTable("dbo.PlannedPMDetails");
            DropTable("dbo.PMStaticJobs");
            DropTable("dbo.DonePMJobs");
            DropTable("dbo.DonePMs");
            DropTable("dbo.PlannedPMs");
            DropTable("dbo.TaskOrderReferences");
            DropTable("dbo.TaskOrderDetails");
            DropTable("dbo.TaskOrders");
            DropTable("dbo.EMStaticJobs");
            DropTable("dbo.EMDetails");
            DropTable("dbo.EMs");
            DropTable("dbo.Products");
            DropTable("dbo.MatUnits");
            DropTable("dbo.MatInvs");
            DropTable("dbo.Mats");
            DropTable("dbo.MatGroups");
            DropTable("dbo.MatGroupTechSpecs");
            DropTable("dbo.DeviceTechSpecs");
            DropTable("dbo.Brands");
            DropTable("dbo.Devices");
            DropTable("dbo.StockDocDetails");
            DropTable("dbo.PlateCharacters");
            DropTable("dbo.Colorings");
            DropTable("dbo.PeopleCars");
            DropTable("dbo.CarBrands");
            DropTable("dbo.OrgCars");
            DropTable("dbo.CarTypes");
            DropTable("dbo.StockDocs");
            DropTable("dbo.Provinces");
            DropTable("dbo.Townships");
            DropTable("dbo.ContractorContacts");
            DropTable("dbo.Contractors");
            DropTable("dbo.DailyCheckLists");
            DropTable("dbo.PlannedCheckLists");
            DropTable("dbo.CheckListTypes");
            DropTable("dbo.CheckListTypeItems");
            DropTable("dbo.CheckListDets");
            DropTable("dbo.CheckLists");
            DropTable("dbo.BranchIPs");
            DropTable("dbo.TimesheetCalendars");
            DropTable("dbo.TimesheetWeekDays");
            DropTable("dbo.PeopleTrafficLicenseWeekDays");
            DropTable("dbo.PeopleTrafficLicenses");
            DropTable("dbo.InvitationTypes");
            DropTable("dbo.Invitations");
            DropTable("dbo.InvitationDepartments");
            DropTable("dbo.BranchDepartments");
            DropTable("dbo.BranchContacts");
            DropTable("dbo.Branches");
            DropTable("dbo.GuardBoards");
            DropTable("dbo.People");
            DropTable("dbo.AttendanceRequests");
            DropTable("dbo.Users");
            DropTable("dbo.Countries");
        }
    }
}
